print("My name is Rahma Ahmed")
print("Age: 20")
print("Department: Electronics and Communications")
print("Graduation Year: 2025")
print("Favourite team: software")
print("City: Alexandria")
print("My GPA: 3.31")
print("Subject I like: Electronics")
print("Subject I don't like: Mechanics")
print("Hobby: Reading")